### ISSUE TITLE
Wie in HA integrieren?

### ISSUE THREAD

**Issue by funkschrauber** [Dielee/DWDAlerts#2]
Hallo,
könntest du mir eben erklären, wie ich das ganze jetzt in HA integriert bekomme?
Download ist klar, aber wo muss ich die Sachen hin kopieren, damit auch der Aufruf erfolgt?

Vielen Dank und Gruß aus Moers

**Comment by Dielee** [comment]
Mahlzeit, brauchst noch hilfe ?

**Comment by funkschrauber** [comment]
Aber sicher :-)

**Comment by Dielee** [comment]
Okay, habe gestern noch ein paar änderungen gepusht. Du kannst es auf irgend einem Linux System als cronjob laufen lassen. Wichtig ist nur das du den MQTT Server oben auf deine passende IP änderst damit dort die Daten auch ankommen.

**Comment by funkschrauber** [comment]
Ähm... da komm ich jetzt nicht wirklich mit weiter.
Ich möchte das gerne in Home Assistant integrieren.
Ich habe ein Pi3 mit Hass.io.
Wo müssen die Dateien hin und wie konfiguriere ich dann die Anzeige für die DWD Wetterwarnung?

**Comment by Dielee** [comment]
Wenn du Hass.io nutzt hast du keine möglichkeit das script zu nutzen. Du benötigst eine linux distro (debian, ubuntu, etc.). Im Hass.io installierst du einen mqtt server.
